.travis.yml
invenio_resources/resources/record.py
invenio_resources/service/__init__.py
invenio_resources/service/actions.py
invenio_resources/service/errors.py
invenio_resources/service/identity.py
invenio_resources/service/resolver.py
invenio_resources/service/search/__init__.py
invenio_resources/service/search/engine.py
invenio_resources/service/search/query.py
invenio_resources/service/search/serializers.py
invenio_resources/service/service.py
invenio_resources/service/state.py
setup.py
tests/service/conftest.py
tests/service/test_service.py

Decision taken based on https://codimd.web.cern.ch/dX2AYr7KRLGZrtqY3-G6iA

service: add records service

---

invenio_records_resources/serializers.py
tests/conftest.py
tests/test_permissions.py
tests/test_record_resource.py

Subsequent API stubs will come later. It took most of my time to discover that these tests were broken and it wasn't my machine.

tests: make them go

---

invenio_records_resources/resources/file.py
invenio_records_resources/resources/record.py
tests/conftest.py
tests/test_permissions.py
tests/test_record_resource.py

closes #22 for real
(the skip is there but Zach will replace it)

global: stub records API

---

invenio_records_resources/resources/file.py
invenio_records_resources/resources/record.py
invenio_records_resources/serializers/__init__.py
invenio_records_resources/serializers/json.py
invenio_records_resources/serializers/xml.py
setup.py
tests/conftest.py
tests/test_permissions.py
tests/test_record_resource.py
tests/test_serialization_integration.py

This is more of a proof of concept than an actual serializer that should be used.
closes: #26

26 datacite xml

---

invenio_records_resources/resources/record.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/record.py
invenio_records_resources/services/search/query.py
invenio_records_resources/services/service.py
setup.py
tests/conftest.py
tests/test_permissions.py
tests/test_record_resource.py

Depends on https://github.com/inveniosoftware/flask-resources/pull/67
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/214

errors: configure resource with error mapping

---

invenio_records_resources/version.py

Need to release to get the flask-resources dependency
Merging this as soon as it passes

release: v0.2.0

---

invenio_records_resources/services/record.py
invenio_records_resources/services/resolver.py
invenio_records_resources/services/search/engine.py
tests/test_record_resource.py

closes #36 
- Fix create test error code. Now 201.
- Make function attributes into singleton properties (makes code smaller and cleaner :) )

Service refactor: syntactic sugar

---

invenio_records_resources/version.py

Bumping minor since it changes the default pid type from recid to recid_v2

release: v0.3.0

---

invenio_records_resources/resources/record.py
invenio_records_resources/services/record.py

- closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/26

resources: remove *args/**kwargs (also services)

---

invenio_records_resources/links.py
invenio_records_resources/resources/record.py
invenio_records_resources/schemas/url_args.py
invenio_records_resources/services/record.py
invenio_records_resources/services/search/engine.py
tests/conftest.py
tests/mock_module/mappings/v6/invenio-records-resources/testrecord.json
tests/mock_module/mappings/v7/invenio-records-resources/testrecord.json
tests/services/test_links.py
tests/services/test_service.py
tests/test_pagination.py
tests/test_permissions.py
tests/test_serialization_integration.py
tests/test_sorting.py

closes #59 
closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/39 for records-resources

59 add back sort to url args

---

invenio_records_resources/links.py
invenio_records_resources/resources/record_config.py
invenio_records_resources/services/record.py
tests/services/test_links.py

close https://github.com/inveniosoftware/invenio-rdm-records/issues/151
Will merge this when tests pass to get releases going and a full installation to test.

links: generate 'files' link

---

invenio_records_resources/resources/__init__.py
invenio_records_resources/resources/record.py
invenio_records_resources/services/service.py
tests/services/test_configuration.py
tests/test_resource_configuration.py

- part of #67
- change in rdm-records needed to fully close the issue

config: make customizable via config.py

---

invenio_records_resources/version.py

release: v0.5.1

---

.github/workflows/pypi-publish.yml
.travis.yml
MANIFEST.in
run-tests.sh
setup.py

Changes:
- Migrate to GH action releases
- Migrate to docker-services-cli
Closes https://github.com/inveniosoftware/invenio-records-resources/issues/37

migrate to new ci features

---

invenio_records_resources/resources/record.py
invenio_records_resources/resources/record_args.py
invenio_records_resources/resources/record_config.py
invenio_records_resources/resources/record_response.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/records/results.py
invenio_records_resources/services/records/schema.py
invenio_records_resources/services/records/service.py
setup.py
tests/resources/test_resources_etag.py
tests/services/test_service_revision_id.py

Depends on https://github.com/inveniosoftware/flask-resources/pull/83

etag: use `if_match` header for optimistic concurrency control

---

invenio_records_resources/records/systemfields/pid.py
invenio_records_resources/services/records/links.py
invenio_records_resources/services/records/search.py
pytest.ini
run-tests.sh
tests/mock_module/api.py
tests/mock_module/models.py
tests/mock_module/permissions.py
tests/mock_module/resource.py
tests/mock_module/schema.py
tests/mock_module/service.py
tests/resources/test_resource_faceting.py
tests/resources/test_resource_pagination.py
tests/resources/test_resource_sorting.py

* Fixes an issue where when a pid was registered the status wasn't updated in the record.

systemfields: serialize pid on record.commit()

---

invenio_records_resources/records/api.py
invenio_records_resources/resources/records/config.py
invenio_records_resources/resources/records/resource.py
invenio_records_resources/services/records/service.py
invenio_records_resources/version.py
setup.py
tests/mock_module/resource.py
tests/resources/test_resource_preference.py

- :warning: Requires https://github.com/inveniosoftware/invenio-search/pull/207 to be released as 1.4.1
- search: port bouncing search results solution
- tests: clean unused URITemplate import
- close #122

search: port bouncing search results solution

---

invenio_records_resources/config.py
invenio_records_resources/ext.py
invenio_records_resources/services/records/results.py
tests/resources/test_resource_links.py

**Proposal**:
- Move delete, files, etc. links to an issue... Otherwise TODOs will get lost in translation.

config: change hostname var name and add links tests

---

invenio_records_resources/services/records/params/sort.py
tests/resources/test_resources.py

* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/359

search: handles empty string with present sort option

---

invenio_records_resources/version.py
setup.py

Resolves inveniosoftware/invenio-rdm-records#257

release: v0.7.4

---

invenio_records_resources/records/systemfields/files.py
tests/records/test_systemfield_files.py

records: add missing files field functionality

---

invenio_records_resources/records/api.py
invenio_records_resources/records/systemfields/files.py
invenio_records_resources/resources/actions/resource.py
invenio_records_resources/resources/files/config.py
invenio_records_resources/resources/files/loaders.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/resources/files/response.py
invenio_records_resources/resources/files/schemas_links.py
invenio_records_resources/services/__init__.py
invenio_records_resources/services/files/__init__.py
invenio_records_resources/services/files/config.py
invenio_records_resources/services/files/results.py
invenio_records_resources/services/files/schema.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/results.py
setup.py
tests/conftest.py
tests/mock_module/api.py
tests/mock_module/resource.py
tests/mock_module/schema.py
tests/mock_module/service.py
tests/records/test_systemfield_files.py
tests/resources/conftest.py
tests/resources/test_files_resource.py
tests/resources/test_resource_links.py
tests/services/conftest.py
tests/services/files/test_file_results.py
tests/services/files/test_file_service.py
tests/services/test_file_service.py

Closes #147, closes #146 , closes #149

File service

---

invenio_records_resources/services/records/service.py
invenio_records_resources/version.py
tests/services/test_service__create.py

- also starts December release series 0.9.X
- part of closing https://github.com/inveniosoftware/invenio-drafts-resources/issues/81

services: allow to create w/o raising errors only reporting

---

.github/workflows/tests.yml
CONTRIBUTING.rst
README.rst
run-tests.sh
setup.py

tests: upgrade to docker-services-cli 0.3.0

---

invenio_records_resources/factories/factory.py
invenio_records_resources/version.py
tests/factories/test_factory.py

The links factory doesn't behave properly; @kprzerwa asked to disable it temporarily.

factories: disable schema links classes

---

LICENSE
invenio_records_resources/services/records/results.py
invenio_records_resources/services/records/service.py
tests/conftest.py
tests/mock_module/service.py
tests/services/test_service.py

Implemented scan() and reindex().
Changed RecordList.total() to return None in case _results do not have 'hits', supposing it's coming from scan().
TODO:
- tests/services/test_service.py:73 reindex() gives kombu.exceptions.InconsistencyError, adding an app_context() does not solve it

service: build basic scan() and reindex() support

---

invenio_records_resources/records/systemfields/pid.py

* Moves create/delete pid code out of the life-cycle hooks so it can be
called outside the life-cycle hooks.

systemfields: factors out create/delete from hooks

---

invenio_records_resources/version.py
setup.py

Starting the initial releases for February. Will merge and release immediately.

release v0.11.0

---

.gitignore
invenio_records_resources/services/records/schema.py
invenio_records_resources/version.py

This is the beginning of a series of PRs + releases to get us a common working environment esp. for access control.
I will leave them out an hour or so before merging and releasing. This is exceptional in the interest of getting us all a working environment on master. 
related to https://github.com/inveniosoftware/react-invenio-deposit/issues/214

clean dump onlys

---

invenio_records_resources/services/records/service.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/563

service: make default_filter configurable

---

invenio_records_resources/services/base/service.py
invenio_records_resources/services/records/results.py
invenio_records_resources/version.py
tests/services/conftest.py
tests/services/test_results.py

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/650
- releases it so that invenio-app-rdm can use it

650 record item permissions for

---

invenio_records_resources/services/records/service.py
setup.py

closes inveniosoftware/invenio-rdm-records#441

service: add method for reindexing all records

---

invenio_records_resources/services/files/results.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/results.py
invenio_records_resources/services/records/schema.py
invenio_records_resources/services/records/service.py

- make responsibilities clearer
- make interface clearer
- this can be merged in the beginning of April along with other refactoring PRs

schema: refactor MarshmallowServiceSchema for clarity [+]

---

invenio_records_resources/config.py
tests/resources/test_resource_faceting.py
tests/resources/test_resource_links.py
tests/resources/test_resource_pagination.py
tests/resources/test_resource_sorting.py

config: harmonise hostname to 127.0.0.1

---

invenio_records_resources/services/files/schema.py
invenio_records_resources/services/records/schema.py
setup.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/741
* needs https://github.com/inveniosoftware/marshmallow-utils/pull/33

services: updates record schema

---

invenio_records_resources/services/records/params/facets.py
invenio_records_resources/services/records/search.py
tests/mock_module/config.py
tests/resources/test_resource_faceting.py
tests/services/test_service_facets.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/440

search: Fix search results for searching resource_type and subtype together

---

invenio_records_resources/services/records/components.py
invenio_records_resources/services/records/config.py
invenio_records_resources/services/records/schema.py
invenio_records_resources/version.py
tests/conftest.py
tests/factories/test_factory.py
tests/factories/test_service.py
tests/mock_module/config.py
tests/mock_module/schemas.py
tests/services/conftest.py

Will wait for other modules' PRs to be ready before marking this non draft.

schemas: remove RecordSchema [+]

---

invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/components.py
invenio_records_resources/version.py
tests/mock_module/api.py
tests/mock_module/config.py
tests/mock_module/schemas.py
tests/resources/test_files_resource.py
tests/services/conftest.py
tests/services/test_files_options.py

files: pass files options via record API

---

invenio_records_resources/services/files/results.py
invenio_records_resources/version.py

requires https://github.com/inveniosoftware/invenio-records-resources/pull/245
closes https://github.com/inveniosoftware/invenio-iiif/issues/38. (doesn't, but to link it) ⚠️

results: open stream

---

invenio_records_resources/services/records/service.py

closes https://github.com/inveniosoftware/invenio-vocabularies/issues/38
(⚠️ IT DOES NOT but i cannot link it otherwise)

services: add es preference and extra filter params to _read_many

---

invenio_records_resources/services/records/facets/facets.py

facets: fix recursive call in nested term labels

---

invenio_records_resources/services/records/service.py

service: add max records limit to read_all and read_many

---

MANIFEST.in
invenio_records_resources/records/jsonschemas/__init__.py
invenio_records_resources/records/jsonschemas/definitions-v1.0.0.json
setup.py

partly closes https://github.com/inveniosoftware/invenio-vocabularies/issues/48

jsonschemas: implement base definitions

---

invenio_records_resources/factories/factory.py
tests/factories/test_factory.py

factories: enable configuration of the pid provider class

---

.gitignore
invenio_records_resources/translations/messages.pot

Todo:
* create a new resource for this module in transifex
* push the .pot file to created resource on transifex

i18n: mark and extract strings for translation

---

invenio_records_resources/records/api.py
invenio_records_resources/version.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/896
supersedes https://github.com/inveniosoftware/invenio-app-rdm/pull/981

api: fix files api attribute retrieval for falsy values

---

invenio_records_resources/services/files/components/metadata.py
invenio_records_resources/services/files/schema.py
setup.py
tests/resources/test_files_resource.py
tests/services/files/test_file_service.py

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/781

files: validate init files via Schema

---

invenio_records_resources/services/records/service.py
invenio_records_resources/version.py

- services: bump record read_many max_records to 150
- release: v0.16.14
- this is the same issue as the other one (my bad for missing it), so I will merge and release directly

release 0 16 14

---

invenio_records_resources/references/registry.py
invenio_records_resources/services/records/service.py
invenio_records_resources/services/uow.py

Reference entity

---

invenio_records_resources/factories/factory.py
invenio_records_resources/records/api.py
invenio_records_resources/records/providers.py
invenio_records_resources/records/resolver.py
invenio_records_resources/records/systemfields/__init__.py
invenio_records_resources/records/systemfields/pid.py
tests/mock_module/models.py
tests/records/test_systemfield_modelpid.py

closes https://github.com/inveniosoftware/invenio-vocabularies/issues/156
**Factory**
- Support customization of model class attributes
- Support customization of record class attributes
- Support customization of pid field constructor parameters
**Systemfields**
- Add `ModelPIDField`: lightweight solution to avoid overloading PIDStore. This field is also in charge of managing its status, stored in another column (e.g. `pid_status`)

factory: customize metadata class attributes

---

invenio_records_resources/services/records/components.py

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/926

service: add relations component

---

invenio_records_resources/services/records/service.py

- The `scan()` method returns elasticsearch `Hit` instances. These have the _recid_ in the `id` property. Therefore the current `res.id` would pass them to the indexer.
- The indexer expects UUIDs, to avoid making a query to pidstore (i.e. avoid using `resolve`, and use `get_record` instead).
In addition, this PR uses source filtering to lighten the load on the query, i.e. get back only the `meta.id` since it is the only value that's useful.

service: pass uuids to bulk indexer

---

invenio_records_resources/services/records/params/pagination.py
invenio_records_resources/services/records/params/querystr.py

services: add query transformer support

---

invenio_records_resources/services/records/params/querystr.py
invenio_records_resources/services/records/queryparser/__init__.py
invenio_records_resources/services/records/queryparser/query.py
invenio_records_resources/services/records/queryparser/suggest.py
invenio_records_resources/services/records/queryparser/transformer.py
tests/services/test_service_queryparser.py

* Adds support for performing query string transformations on the
abstract syntax tree of the query.
* Adds SearchFieldTransformer for mapping field names to internal
fields.
**Reminder**
1. You license your contribution under the same …

services: query string search field mapping

---

invenio_records_resources/resources/records/config.py
invenio_records_resources/resources/records/resource.py

inveniosoftware/invenio-communities#556

Requests: allow refresh boolean argument

---

invenio_records_resources/factories/factory.py
invenio_records_resources/services/records/config.py
tests/factories/test_service.py

- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/190

Indexer queue name

---

invenio_records_resources/__init__.py

release: v0.19.15

---

invenio_records_resources/translations/de/LC_MESSAGES/messages.po

* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664

i18n: adds german translation

---

invenio_records_resources/factories/factory.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1518

factory: add resource attributes

---

invenio_records_resources/__init__.py

release: v0.19.17

---

invenio_records_resources/services/custom_fields/base.py
invenio_records_resources/services/custom_fields/service.py

- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/205

cf base properties

---

invenio_records_resources/services/custom_fields/base.py
invenio_records_resources/services/custom_fields/schema.py

rename custom to custom_fields

---

invenio_records_resources/services/custom_fields/base.py
invenio_records_resources/services/custom_fields/schema.py
tests/services/custom_fields/test_base_cf.py
tests/services/custom_fields/test_schema_cf.py

cf: add namespace

---

invenio_records_resources/services/custom_fields/schema.py
tests/services/custom_fields/test_schema_cf.py

cf: test prefixed names i.e namespaces

---

invenio_records_resources/services/custom_fields/errors.py
invenio_records_resources/services/custom_fields/validate.py
tests/services/custom_fields/test_validate.py

- closes https://github.com/inveniosoftware/invenio-records-resources/issues/361

custom fields: add validation and errors

---

invenio_records_resources/services/custom_fields/mappings.py

custom fields: add field exists in mapping and properties extraction

---

invenio_records_resources/__init__.py
invenio_records_resources/services/base/config.py

services: add config creation and loading methods

---

invenio_records_resources/services/custom_fields/__init__.py
invenio_records_resources/services/custom_fields/boolean.py
invenio_records_resources/services/custom_fields/mappings.py
invenio_records_resources/services/custom_fields/number.py
tests/services/custom_fields/test_boolean_cf.py
tests/services/custom_fields/test_number_cf.py

Bool and int cf

---

CHANGES.rst
invenio_records_resources/__init__.py

- closes https://github.com/inveniosoftware/invenio-records-resources/issues/428

release: v1.0.2

---

invenio_records_resources/services/records/service.py

* Closes #431.
* Use a lighter SQL query for fetching record IDs.
* Pass a generator to the bulk indexing call.
**Reminder**
1. You license your …

services: fix rebuild index memory usage

---

CHANGES.rst
invenio_records_resources/__init__.py
invenio_records_resources/references/resolvers/base.py
invenio_records_resources/references/resolvers/records.py
invenio_records_resources/services/base/links.py
invenio_records_resources/services/files/results.py
invenio_records_resources/services/records/results.py
tests/services/test_results_expand.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1987

expand: pass identity when picking fields

---

invenio_records_resources/services/base/config.py

closes https://github.com/zenodo/zenodo-rdm/issues/102

searchs: added query parse cls to search config

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v1.0.4

---

invenio_records_resources/resources/errors.py
invenio_records_resources/services/errors.py

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1952

errors: add facet not found

---

CHANGES.rst
invenio_records_resources/__init__.py
invenio_records_resources/resources/files/config.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/custom_fields/date.py
setup.cfg
tests/mock_module/config.py
tests/records/test_systemfield_files.py
tests/resources/test_files_resource.py
tests/resources/test_resource_links.py
tests/services/files/test_file_service.py
tests/services/test_results_expand.py

Addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/2037.
Implemented an all-in-one-download of all files of a record (a streaming solution, so memory and hard-disk consumption is only minimal)
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repositor …

Implemented an all-in-one-download

---

invenio_records_resources/services/base/__init__.py
invenio_records_resources/services/base/utils.py
tests/services/test_utils.py

* closes https://github.com/inveniosoftware/invenio-banners/issues/11

utils: add search query parameters parser

---

CHANGES.rst
invenio_records_resources/__init__.py
invenio_records_resources/services/__init__.py
invenio_records_resources/services/records/__init__.py
invenio_records_resources/services/records/service.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1163

service: add Record Indexer Service mixin

---

invenio_records_resources/services/files/schema.py
invenio_records_resources/services/files/transfer.py
tests/services/files/test_file_service.py

* closes https://github.com/inveniosoftware/invenio-records-resources/issues/438

files : serialize uri only for non-local files

---

invenio_records_resources/notifications.py
invenio_records_resources/services/uow.py
setup.cfg

closes #440 #450 
depends on https://github.com/inveniosoftware/invenio-notifications/pull/8
Add a simple `NotificationOp`
Add `invenio_notifications` to dependencies
Add add base builder, generator, filter and transformer
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-un …

service: add NotificationOp

---

invenio_records_resources/services/custom_fields/base.py
invenio_records_resources/services/custom_fields/boolean.py
invenio_records_resources/services/custom_fields/date.py
invenio_records_resources/services/custom_fields/errors.py
invenio_records_resources/services/custom_fields/number.py
invenio_records_resources/services/custom_fields/text.py
tests/services/custom_fields/test_boolean_cf.py
tests/services/custom_fields/test_date_cf.py
tests/services/custom_fields/test_number_cf.py
tests/services/custom_fields/test_text_cf.py

closes https://github.com/inveniosoftware/invenio-records-resources/issues/459
Needs to be backported in v11!

custom-fields: properly handle field_cls customization

---

invenio_records_resources/services/records/service.py

* param version is not allowed in count queries, therfore has to be optional
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2092

services: enable count on searches

---

invenio_records_resources/services/records/queryparser/transformer.py
tests/services/test_service_queryparser.py

closes https://github.com/inveniosoftware/invenio-records-resources/issues/447

queryparser: added safelisting of terms

---

invenio_records_resources/services/records/queryparser/query.py
invenio_records_resources/services/records/queryparser/transformer.py
tests/services/test_service_queryparser.py

- closes https://github.com/inveniosoftware/invenio-records-resources/issues/464

queryparser: calculate mapping, allow list and fields

---

invenio_records_resources/factories/factory.py
invenio_records_resources/records/api.py
invenio_records_resources/records/dumpers.py
invenio_records_resources/records/jsonschemas/definitions-v2.0.0.json
invenio_records_resources/records/systemfields/files/field.py
invenio_records_resources/records/systemfields/files/manager.py
tests/conftest.py
tests/factories/test_factory.py
tests/mock_module/api.py
tests/mock_module/jsonschemas/records/record-nofiles-v1.0.0.json
tests/mock_module/jsonschemas/records/record-v1.0.0.json
tests/mock_module_factory/jsonschemas/grants/grant-v1.0.0.json
tests/records/test_systemfield_files.py

* Adds support for dumping file metadata into records when indexed so that the metadata is available for searching.
* Changes data structure of how a file is stored inside a record, however the feature was not used and hence no data has been stored.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository …

records: add file metadata indexing

---

invenio_records_resources/references/entity_resolvers/__init__.py
invenio_records_resources/references/entity_resolvers/base.py
invenio_records_resources/references/entity_resolvers/results.py
invenio_records_resources/references/registry.py

* closes https://github.com/inveniosoftware/invenio-notifications/issues/5
adapt parsing reference dict, as it may get an entity which does not inherit from dict

resolvers: add ResultItemResolver

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.4.0

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.8.0

---

CHANGES.rst
invenio_records_resources/__init__.py
invenio_records_resources/resources/errors.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/files/schema.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/files/tasks.py
invenio_records_resources/tasks.py
tests/resources/test_files_resource.py
tests/services/files/test_file_service.py

Backport of the following two PRs:
* https://github.com/inveniosoftware/invenio-records-resources/pull/449
* https://github.com/inveniosoftware/invenio-records-resources/pull/454

Backport of file-related fixes to v1.0.x

---

.github/workflows/tests.yml
invenio_records_resources/records/systemfields/files/field.py

closes https://github.com/zenodo/rdm-project/issues/166

files: add flag to dump files count

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v1.10.0

---

CHANGES.rst

release: v4.10.0

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.10.1

---

invenio_records_resources/records/systemfields/files/manager.py

files: set bucket quota

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.11.0

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.11.1

---

invenio_records_resources/records/api.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2408

api: fix bool comparison

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.11.2

---

invenio_records_resources/services/records/params/facets.py
invenio_records_resources/services/records/params/pagination.py

closes https://github.com/inveniosoftware/invenio-records-resources/issues/515

params: deepcopy service config dicts to avoid mutation bugs

---

invenio_records_resources/services/records/service.py

service: add extra_filter to reindex method

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.11.5

---

invenio_records_resources/services/errors.py
invenio_records_resources/services/files/components/content.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/files/transfer.py

* closes https://github.com/zenodo/rdm-project/issues/253
* partially addresses https://github.com/inveniosoftware/invenio-records-resources/issues/319
this and dependent PRs need to be reviewed and tested **very** thoroughly

components: handle file upload interruption

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.11.6

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.13.0

---

invenio_records_resources/services/custom_fields/date.py
setup.cfg

Closes https://github.com/zenodo/rdm-project/issues/328

services: custom_fields: date: use parse_edtf from babel-edtf

---

tests/services/custom_fields/test_date_cf.py

tests: update edtf tests

---

invenio_records_resources/resources/files/config.py
invenio_records_resources/services/files/config.py

Closes Issue [#363](https://github.com/zenodo/rdm-project/issues/363)
**Reminder**
2. You agree that you …

files: allowing slash in filename

---

CHANGES.rst
invenio_records_resources/__init__.py

release: v4.16.3

---

invenio_records_resources/records/api.py
invenio_records_resources/records/systemfields/files/manager.py
tests/records/test_systemfield_files.py

* closes https://github.com/zenodo/rdm-project/issues/413
* NEEDS https://github.com/inveniosoftware/invenio-files-rest/pull/298

manager: update delete_all

---

invenio_records_resources/services/files/schema.py

Closes Issue [#488](https://github.com/zenodo/rdm-project/issues/488)
**Reminder**
2. You agree that you …

files: changed the type of file key to string

---

invenio_records_resources/services/records/service.py

Dependecy of https://github.com/inveniosoftware/invenio-rdm-records/pull/1629
Fixes: https://github.com/inveniosoftware/invenio-rdm-records/issues/1291

records: service: add permission check action as parameter

---

invenio_records_resources/resources/errors.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/files/components/metadata.py
invenio_records_resources/services/files/config.py

* closes https://github.com/zenodo/rdm-project/issues/514

files: handle files amount exceeding max limit when adding files via rest api

---

invenio_records_resources/services/files/processors/image.py

closes https://github.com/zenodo/ops/issues/311

processors: updated file metadata extractor.

---

invenio_records_resources/records/systemfields/calculated.py
invenio_records_resources/services/records/service.py

* Moved from invenio-users-resources.
* Allows calculated system field to cache the value in the index, and use the cached value when reading from the index.
closes https://github.com/zenodo/ops/issues/398

records: add calculated system field with indexing

---

invenio_records_resources/factories/factory.py
invenio_records_resources/services/__init__.py
invenio_records_resources/services/base/__init__.py
invenio_records_resources/services/base/links.py
invenio_records_resources/services/records/results.py
invenio_records_resources/services/records/service.py
tests/mock_module/config.py

Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1291
Replacement of https://github.com/inveniosoftware/invenio-rdm-records/pull/1629

services: Add support for nested links

---

CHANGES.rst
invenio_records_resources/__init__.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/records/service.py

* closes https://github.com/inveniosoftware/product-rdm/issues/178

errors: rework PermissionDeniedError

---

invenio_records_resources/services/records/service.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2685

services: clean up the code

---

invenio_records_resources/services/base/config.py
invenio_records_resources/services/base/results.py
invenio_records_resources/services/base/service.py
invenio_records_resources/services/records/config.py
invenio_records_resources/services/records/results.py
invenio_records_resources/services/records/service.py
invenio_records_resources/services/uow.py
tests/services/conftest.py
tests/services/test_service_create_update.py

* closes https://github.com/inveniosoftware/invenio-vocabularies/issues/353
* NEEDS https://github.com/inveniosoftware/invenio-records-permissions/pull/100

service: add create update many

---

invenio_records_resources/services/files/transfer.py

Closes Issue: https://github.com/inveniosoftware/invenio-rdm-records/issues/1788
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree …

files: update for retriveing files bucket

---

CHANGES.rst
invenio_records_resources/__init__.py

> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder** …

release: v6.4.0

---

.github/workflows/pypi-publish.yml
CHANGES.rst
invenio_records_resources/__init__.py
setup.cfg

- setup: bump major dependencies
- setup: change to reusable workflows
- release: v7.0.0

bump major

---

CHANGES.rst
invenio_records_resources/__init__.py

> Please describe briefly your pull request.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

release: v5.11

---

CHANGES.rst
invenio_records_resources/__init__.py

> Please describe briefly your pull request.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

release: v5.11.1

---

CHANGES.rst
invenio_records_resources/__init__.py
invenio_records_resources/resources/files/config.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/base/links.py
invenio_records_resources/services/files/config.py

- **urls: locate Link warning more appropriately [+]**
- **config: move allow_{upload,archive_download} to service [+]**
- **release: v7.3.0**

make file url rules depend on service

---

tests/resources/test_files_resource.py

This PR adds tests to make sure HTTP Range requests are propagated from the `ObjectVersion` correctly.
It does not change any code.
*Note:* needs changes in https://github.com/inveniosoftware/invenio-files-rest/pull/329 to work (edge case handling)
**Frontend**
**Reminder**
1. …

HTTP Range tests

---

CHANGES.rst
invenio_records_resources/__init__.py

> Please describe briefly your pull request.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

release: v8.6.0
