inveniosoftware/invenio-records-resources

.editorconfig
.travis.yml
invenio_resources/config.py
invenio_resources/links.py
invenio_resources/resources/record.py
invenio_resources/responses.py
invenio_resources/schemas/json.py
invenio_resources/serializers.py
invenio_resources/service/__init__.py
invenio_resources/service/actions.py
invenio_resources/service/errors.py
invenio_resources/service/identity.py
invenio_resources/service/resolver.py
invenio_resources/service/search/__init__.py
invenio_resources/service/search/engine.py
invenio_resources/service/search/query.py
invenio_resources/service/search/serializers.py
invenio_resources/service/service.py
invenio_resources/service/state.py
run-tests.sh
setup.py
tests/api/test_record_resource.py
tests/service/conftest.py
tests/service/test_service.py

closes #13 
closes #12 
- Adds a `RecordSearchState` object to be able to pass to the serializer the whole content in a meaningful way
- Linking still has some issues on how to obtain the url parameters to add to search links. Single record links are already *ok*.
Example response:
```json
{
"hits":{
"hits":[
{
"pid":"1",
"metadata":{
"_access":{
"metadata_restricted": False,
"files_restricted": False
},
"_owners":[
1
],
"_created_by":1,
"access_right":"open",
"resource_type":{
"type":"image",
"subtype":"image-photo"
},
"creators":[
],
"titles":[
{
"title":"A Romans story",
"type":"Other",
"lang":"eng"
}
],
"publication_date":"2020-07-07",
"_publication_date_search":"2020-07-07",
"recid":"1"
},
"revision":-1,
"created":"None",
"updated":"None",
"links":{ …
```

Response: support for total, aggregations and links

---

invenio_records_resources/resources/record.py
invenio_records_resources/schemas/__init__.py
invenio_records_resources/schemas/fields/__init__.py
invenio_records_resources/schemas/fields/sanitized_unicode.py
invenio_records_resources/schemas/json.py
invenio_records_resources/service/__init__.py
invenio_records_resources/service/data_validator.py
invenio_records_resources/service/service.py
tests/conftest.py
tests/service/test_data_validator.py
tests/test_record_resource.py

- Support using marshmallow schemas
- Refactor current schemas to support a non RDM tight metadata schema
- Refactor tests to reflect the new schemas
- Tests:
- Test data validator interface (for coverage reasons only)
- Tests default marshmallow data validator
- Test  marshmallow data validator with custom schema
- Test request with validation error commented out, because it throws an exception. Error handling will solve this issue.
Careful if https://github.com/inveniosoftware/invenio-resources/pull/24 is merged before. It implies a rebase and refactor on the tests structure.

service: support data validation

---

invenio_records_resources/services/record.py
tests/test_record_resource.py

requires #36
There is a need to encapsulate pids management (resolver, minter, fetcher, types, even versioning). It will be addressed in a different PR.

split pid types

---

.travis.yml
MANIFEST.in
requirements-devel.txt
setup.py
tests/conftest.py
tests/mock_module/__init__.py
tests/mock_module/mappings/__init__.py
tests/mock_module/mappings/v6/__init__.py
tests/mock_module/mappings/v6/invenio-records-resources/testrecord.json
tests/mock_module/mappings/v7/__init__.py
tests/mock_module/mappings/v7/invenio-records-resources/testrecord.json
tests/test_record_resource.py

close #19 
`test_read_record_with_different_type_of_redirected_pid` is now failing on my machine... It actually raises the exception instead of serializing to a 500. I know pidstore and error handling have been modified recently. What am I missing?

fix: test search correctly

---

invenio_records_resources/config.py
invenio_records_resources/links.py
invenio_records_resources/pagination.py
invenio_records_resources/resource_units.py
invenio_records_resources/resources/record.py
invenio_records_resources/resources/record_config.py
invenio_records_resources/schemas/__init__.py
invenio_records_resources/schemas/url_args.py
invenio_records_resources/serializers/json.py
invenio_records_resources/serializers/xml.py
invenio_records_resources/services/file_metadata.py
invenio_records_resources/services/record.py
invenio_records_resources/services/service.py
tests/conftest.py
tests/test_links.py
tests/test_pagination.py
tests/test_serialization_integration.py

- parse URL querystring
* size
* page
* q
- generate search self, next, prev links
- generate read self, self_html
- pass down URL routes from RecordServiceConfig
* required splitting ResourceRecordconfig in own file
- keeps ResourceUnit + ResourceList as data containers
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/212
- closes #33 
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/131

Search records epic

---

invenio_records_resources/links.py
invenio_records_resources/version.py

- Instead of accessing config in constructor, config is
accessed when `.route` is called which is always in
app context.
- bumps version to 0.4.1
This is part of making a working August release and will be merged and deployed when it passes.

links: access config in app context

---

invenio_records_resources/links.py
invenio_records_resources/services/record.py
tests/services/test_links.py

LinkBuilders are now initialized in an app_context, so
no need for trick anymore.
part of https://github.com/inveniosoftware/invenio-app-rdm/issues/232

links: revert self_html back into __init__ [more]

---

invenio_records_resources/pagination.py
invenio_records_resources/resources/errors.py
invenio_records_resources/resources/record_args.py
invenio_records_resources/resources/record_config.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/records/config.py
invenio_records_resources/services/records/params/pagination.py
tests/resources/conftest.py
tests/resources/test_faceting.py
tests/resources/test_resource_pagination.py
tests/resources/test_sorting.py
tests/services/test_service_pagination.py
tests/services/test_service_sort.py

- Service level defaults are used for pagination
- Pagination errors are dealt at the service level
- Link generation is pushed off to another issue.
- closes #56

search: test sort, facet, pagination endpoints [+]

---

setup.py

Depends on invenio-celery 1.2.1 or pytest-invenio 1.4.0

installation: remove celery dependency

---

invenio_records_resources/services/records/params/querystr.py
invenio_records_resources/version.py
tests/resources/test_resource_faceting.py
tests/resources/test_resource_pagination.py
tests/resources/test_resource_sorting.py
tests/resources/test_resources.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/284
```
ipdb> params
{'q': ''}
> /Users/ppanero/Workspace/inveniosw/invenio-records-resources/invenio_records_resources/services/records/params/querystr.py(41)apply()
35         if query_str is None:
36             return search
37
38         try:
39             parser_cls = self.config.search_query_parser_cls
40             query = parser_cls(identity).parse(query_str)
---> 41             return search.query(query)
42         except SyntaxError:
43             # TOOD: raise a proper type of exception
44             raise Exception("Failed to parse query.")
ipdb> query
QueryString(query='')
```
This makes the search *match empty*
**correct search**
```
{'query': {'bool': {'minimum_should_match': '0<1', 'filter': …
```

tests: resource level search with empty query

---

invenio_records_resources/services/records/params/sort.py

React searchkit appends in the url the `?q` parameter even if is empty string. As a matter of fact, the search application has a configuration variable for choosing the default sort option on empty querystring. In the SortInterpreter we were just checking if the q is in the URL params without checking its value

sort: check if `q` param is empty

---

invenio_records_resources/services/records/results.py
tests/services/conftest.py
tests/services/test_links.py
tests/services/test_service.py

Closes https://github.com/inveniosoftware/invenio-records-resources/issues/123
Tests added at service level with a mock of the links schema. If the resources define the proper schema links, they will be rendered (tested this manually and is correct).
**Question**: @lnielsen 
Should this task also include the addition of `delete`, `list` etc. links in for the record? Meaning changing `resources/records/schema_links.py` and implementing tests for them?

service: add links to hits of a search result

---

invenio_records_resources/version.py
run-tests.sh
setup.py

- Merging this as it passes since it's an update to the CI.
- bumping to 0.9.1 to not have to alter the tag on master (don't want to alter master beyond adding releases)

ci: don't upgrade to docker-services-cli 0.3.0

---

invenio_records_resources/errors.py
invenio_records_resources/resources/actions/config.py
invenio_records_resources/resources/errors.py
invenio_records_resources/resources/records/config.py
invenio_records_resources/services/records/schema.py
setup.py
tests/services/test_service__create.py

Now all schema validation errors should lead to
```
'errors': [{'field': ..., 'message': ...}, ...]
```
entry in final json.
requires: https://github.com/inveniosoftware/flask-resources/pull/89

errors: serialize schema errors uniformly

---

invenio_records_resources/records/systemfields/files.py
invenio_records_resources/version.py
tests/records/test_systemfield_files.py

* Fixes issue with "order" and "default_preview" keys being stored even
if they are none or empty.

systemfields: fix files field json serialization

---

invenio_records_resources/services/files/service.py

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/401
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/406
- enforces all file permissions 
- required for https://github.com/inveniosoftware/invenio-rdm-records/pull/402 (tests really reside)
- fixes some file deletion code that was broken

permissions: enforce files permissions

---

invenio_records_resources/services/records/service.py

* Refreshes the index when deleting an record, as the user is often
redirect straight after to a search results which often will include
the just deleted record.

services: refresh index on delete

---

invenio_records_resources/services/records/results.py
setup.py

closes inveniosoftware/invenio-rdm-records#439
in `ResultItem.data`, the `record` keyword argument was missing from the call to `self._service.schema.dump()`, causing the `record` argument in the permission generators to be set to `None`

services: specify record kwarg for schema.dump in ResultItem

---

invenio_records_resources/resources/errors.py
tests/resources/test_resources.py

* Adds error handlers for wrong json data and
wrong ES request
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/497

errors: json and ES errors

---

invenio_records_resources/records/systemfields/files/manager.py
invenio_records_resources/resources/files/config.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/files/config.py
invenio_records_resources/services/files/service.py
tests/mock_module/resource.py
tests/resources/test_files_resource.py

closes https://github.com/inveniosoftware/invenio-rdm-records/issues/498
- Added a  `allow_upload` config value to FileResource to enable/disable file upload
- Added a `permission_action_prefix` config value to FileService to allow to define a prefix for differentiated permissions in permission policy
- Throw more specific exceptions for file errors in FilesManager to prevent returning 500 server error e.g when same file is uploaded second time

resources/services: config that can enable/disable file upload

---

invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/components.py
invenio_records_resources/services/records/config.py
invenio_records_resources/services/records/schema.py
tests/conftest.py
tests/factories/test_factory.py
tests/factories/test_service.py
tests/mock_module/config.py
tests/mock_module/schemas.py
tests/resources/conftest.py
tests/resources/test_files_resource.py
tests/resources/test_resource_faceting.py
tests/resources/test_resource_links.py
tests/resources/test_resource_pagination.py
tests/resources/test_resource_sorting.py
tests/resources/test_resources.py
tests/services/__init__.py
tests/services/conftest.py
tests/services/files/test_file_service.py
tests/services/files_utils.py
tests/services/test_files_options.py

- part of closing #225
* defines component to assign `files.enabled`
* ended up having to do the majority of the changes here because file addition is defined in this package
- renames `tests/mock_module/service.py` -> `tests/mock_module/config.py`
- removes `unknown = INCLUDE` in keeping with previous work (see https://github.com/inveniosoftware/invenio-rdm-records/issues/496)
- moves some fixtures up the hierarchy so they can be reused

files: enable/disable files via record body

---

setup.py

@lnielsen marshmallow-utils got only a change in API (and behaviour) in the IdentifierScheme schema, should not affect any of this module, but we need it for the pids work.

dependencies: bump marshmallow-utils

---

invenio_records_resources/records/systemfields/files/manager.py
tests/records/test_systemfield_files.py

* Fixes an issues where object versions was soft-deleted instead of
hard-deleted, thus leaving the files behind.

files: hard remove object versions

---

invenio_records_resources/records/systemfields/pid_statuscheck.py

* The dumps() and loads() method should be idempotent and produce the
same dict version of a record.

systemfields: PIDStatusCheckField idempotence

---

invenio_records_resources/records/api.py
invenio_records_resources/services/files/results.py

Why is this needed?
- Flask-IIIF is expecting a byte stream:
- Which will be obtained (not read), [here](https://github.com/inveniosoftware/flask-iiif/blob/0f48cb3b5ba43170eca7aa0d2ff14205c8d08497/flask_iiif/restful.py#L76)
- And passed to Pillow for opening [here](https://github.com/inveniosoftware/flask-iiif/blob/0f48cb3b5ba43170eca7aa0d2ff14205c8d08497/flask_iiif/api.py#L580)
- **Important issue** It seems nobody `close()`s the stream....
**In order not to change the API**, and therefore have to change Flask-IIIF, we must return a byte stream. That means, that we cannot use the `open_stream` context manager (because it would close the stream when `return`ing). It will be generated by the `image_opener_handler` created in [`invenio-rdm-records`](https://github.com/inveniosoftware/invenio …

files: add method to return a file stream

---

invenio_records_resources/services/records/service.py

We have 100+ resource types at NU so that limit constantly crashes selection
of certain resource types. We have other vocabularies that have the potential
to grow past 100 as well.
Tracking every use of read_all is unfeasible so making the change here.
Until we figure out a better way to address these instance-specific
scaling concerns, I am bumping the default max_records so that
this works for us and probably others.

services: bump record read_all max_records to 150

---

invenio_records_resources/services/base/components.py
invenio_records_resources/services/base/service.py
invenio_records_resources/services/files/components/base.py
invenio_records_resources/services/files/components/processor.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/components.py
invenio_records_resources/services/records/service.py
invenio_records_resources/services/uow.py
setup.py

* Adds a new Unit of Work context manager used to allow atomic
operations over multiple service calls.
* Keeps API as backwards compatible as possible.

service: add "unit of work" for atomic operations

---

invenio_records_resources/factories/factory.py
invenio_records_resources/version.py

- closes https://github.com/inveniosoftware/invenio-records-resources/issues/289
- It does not break compatibility.
- Before merging we should make a version bump so it does not go into the previous LTS, however it can go in the next independently of the ORCiD integration due to the point below.

factory: add support for record relations

---

invenio_records_resources/resources/files/resource.py
invenio_records_resources/resources/records/resource.py
invenio_records_resources/services/files/components/base.py
invenio_records_resources/services/files/components/content.py
invenio_records_resources/services/files/components/metadata.py
invenio_records_resources/services/files/components/processor.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/service.py
invenio_records_resources/tasks.py
tests/factories/test_service.py
tests/services/files/files_utils.py
tests/services/files/test_file_service.py
tests/services/files/test_files_options.py
tests/services/files/test_files_processing.py
tests/services/test_service.py
tests/services/test_service_revision_id.py

- closes #258 
- Because this PR changes some function declarations, other (see below) PRs in other repos will need to be merged as well. Then a version bump should be required, but since at time of writing 0.18 has been made and is not part of the LTS or STS, we can piggy back on it I think (0.18.2 for instance). 
Downstream PRs:
- https://github.com/inveniosoftware/invenio-drafts-resources/pull/175
- https://github.com/inveniosoftware/invenio-vocabularies/pull/121
- https://github.com/inveniosoftware/invenio-requests/pull/101
- https://github.com/inveniosoftware/invenio-communities/pull/375
- https://github.com/inveniosoftware/invenio-rdm-records/pull/863
- https://github.com/inveniosoftware/invenio-app-rdm/pull/1154

services: order methods consistently with identity first

---

invenio_records_resources/records/jsonschemas/definitions-v1.0.0.json
invenio_records_resources/records/systemfields/calculated.py
invenio_records_resources/records/systemfields/entity_reference.py
invenio_records_resources/references/__init__.py
invenio_records_resources/references/registry.py
invenio_records_resources/references/resolvers/__init__.py
invenio_records_resources/references/resolvers/base.py
invenio_records_resources/references/resolvers/records.py
invenio_records_resources/references/resolvers/users.py
invenio_records_resources/services/records/schema.py
invenio_records_resources/services/references/__init__.py
invenio_records_resources/services/references/schema.py

Partially closes https://github.com/inveniosoftware/invenio-requests/issues/12
In a follow-up task, we should probably adjust the owners structure in the parent records' access field (https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/systemfields/access/owners.py) to use the newly created mechanisms

Lift up entity reference stuff from Invenio-Requests

---

invenio_records_resources/records/systemfields/entity_reference.py
invenio_records_resources/version.py

Some helper functions were accidentally lifted that aren't useful outside of Invenio-Requests.
Also, this bumps the version to v0.18.3

Remove accidentally lifted-up helper functions from Invenio-Requests

---

invenio_records_resources/services/records/params/facets.py
tests/mock_module/config.py
tests/mock_module/mappings/v6/records/record-v1.0.0.json
tests/mock_module/mappings/v7/records/record-v1.0.0.json
tests/mock_module/schemas.py
tests/resources/test_resource_faceting.py
tests/services/test_service_facets.py

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1263

fix: intersect different filter categories instead of union

---

invenio_records_resources/__init__.py
invenio_records_resources/services/records/service.py

Making the queue lazy avoids errors when registering the indexers in the views (rdm-records), since at that point there is no app ctx pushed and we need to access `current_app`.

service: make queue lazy (local proxy)

---

invenio_records_resources/services/records/service.py
tests/conftest.py
tests/services/conftest.py

The routing key was defined at queue level, however the publish method was using that of the producer. This lead to messages being sent to two queues. For example on community members update it was sending to `members` (queue level routing key) and `records` (producer level routing key - default)

service: set indexer routing key at producer level

---

invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/files/service.py

At the moment when requesting from an endpoint that expects to receive a filename (for example `/api/records/{record_id}/files/{filename}`) and the filename does not exist, it will throw an internal server error, it should gracefully return that the resource does not exist. 
Added error catching when a file is being looked up based on it's `key/filename `, if a key error is raised it will return a 404 error to the user.
closes https://github.com/inveniosoftware/invenio-records-resources/issues/347

record files: add error response for unknown files

---

invenio_records_resources/services/custom_fields/__init__.py
invenio_records_resources/services/custom_fields/base.py
invenio_records_resources/services/custom_fields/text.py
tests/services/custom_fields/test_text_cf.py

- closes #386 
This enables removing duplicated code. See #387, where both date fields need to reimplement the logic of `if multiple...`. Now it gets delegated to the `BaseListCF` class.

custom fields: simplify implementation of multiple values (list)

---

invenio_records_resources/services/records/facets/facets.py

facets: add support for cf nested terms

---

invenio_records_resources/records/dumpers.py
invenio_records_resources/services/custom_fields/__init__.py
invenio_records_resources/services/custom_fields/base.py
invenio_records_resources/services/custom_fields/date.py
invenio_records_resources/services/custom_fields/text.py
tests/records/test_dumpers.py
tests/services/custom_fields/test_date_cf.py

custom fields: edtf and iso date support

---

tests/mock_module/config.py
tests/resources/test_files_resource.py
tests/services/files/conftest.py
tests/services/test_service_relation_propagation.py

Fixes mock service naming, as per convention (_record type, without the `-service`_).

tests: consisten mock service naming

---

invenio_records_resources/config.py
invenio_records_resources/records/jsonschemas/definitions-v1.0.0.json
invenio_records_resources/records/systemfields/files/manager.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/files/components/content.py
invenio_records_resources/services/files/components/metadata.py
invenio_records_resources/services/files/generators.py
invenio_records_resources/services/files/schema.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/files/tasks.py
invenio_records_resources/services/files/transfer.py
setup.cfg
tests/conftest.py
tests/mock_module/permissions.py
tests/services/files/test_file_service.py

- closes https://github.com/inveniosoftware/invenio-records-resources/issues/408
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/410
Now there will be two "workflows" to upload files:
a) if the payload **does not** contain a `uri`/`sotrage_class==E` it goes as before: `init` will create the file record (no object version nor file instance), Then requests to `/content` and `/commit` are needed from the user to get the file in.
b) if the payload **does** contain a `uri`/`sotrage_class==E`, the `init` creates an object version and a file instance, and triggers the task to do a `set_content` and `commit`. Those actions are forbiden by the user.

services: implement file fetching from external storage

---

invenio_records_resources/services/records/service.py

Make the `service.rebuild_index` method use bulk indexing rather than indexing each item individually.

Bulk indexing for `rebuild_index`

---

invenio_records_resources/services/files/schema.py
invenio_records_resources/services/files/tasks.py
invenio_records_resources/services/files/transfer.py

Sample response with new status:
```
{'mimetype': 'application/zip', 'status': 'pending', 'uri': 'https://zenodo.org/record/4008297/files/dataset.zip#3', ...}
```

file service: make status aware of fetch files

---

invenio_records_resources/resources/errors.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/files/tasks.py
invenio_records_resources/tasks.py
tests/services/files/test_file_service.py

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1998
This PR introduces a new custom error type: `FileKeyNotFoundError` to denote when the service was trying to access a non-existing file key for a record.

Add new `FileKeyNotFoundError`

---

invenio_records_resources/services/files/schema.py
tests/resources/test_files_resource.py

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2032
This PR addresses the issue that empty files (with size 0) blow up record landing pages with an error message stating `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'size'`.
I have a feeling that there's a better way of doing this that involves the [`schema.fields_from_file_obj`](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/files/schema.py#L77), but I'll have to check some more.
Potentially it also has to do with 0 being the "null" value for integers in the database model?

Fix "size" field missing on empty files

---

invenio_records_resources/services/records/service.py
setup.cfg
tests/services/test_service_relation_propagation.py

* the reindex of records on relation update was not limiting the number of records given as input. For large number of records, the search engine fails because of too many search clauses added to the search query..

relations: reindex by chunk

---

invenio_records_resources/services/records/params/sort.py
invenio_records_resources/services/records/service.py
invenio_records_resources/services/uow.py

closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1398
WHY THIS PR:
- I need to implement a type of `SortParam`, where the `fields` are computed in the same way as the parent except that, in the new interpreter, the fields are always prepended by a new field.
- To avoid code duplication, I refactored the `apply` method to just apply the fields to the search's sort instead of computing the fields + applying them.
- Added a service call to reindex records by the latest version first. 
- The idea is to speed up the reindexing of the latest versions while the other versions can be done, in bulk, separately. 
- Added a new UOW operation for bulk indexing records, given an iterable of ids (e.g. a generator)

params: refactored sort fields computation.

---

invenio_records_resources/services/records/service.py

* closes https://github.com/inveniosoftware/invenio-records-resources/issues/486
Note: the only usage: https://github.com/inveniosoftware/invenio-rdm-records/blob/0728b74cfd98c92616485b71d259fc224a8a60f9/invenio_rdm_records/requests/user_moderation/actions.py#L32

services: move reindex latest records to drafts-resources

---

invenio_records_resources/records/systemfields/files/field.py

Conditional dumping

---

invenio_records_resources/services/base/links.py
invenio_records_resources/services/records/links.py
invenio_records_resources/services/records/service.py

closes https://github.com/zenodo/rdm-project/issues/11

records: added link template for read_many calls.

---

invenio_records_resources/resources/errors.py
invenio_records_resources/resources/files/resource.py
invenio_records_resources/services/files/service.py

files: abort with 500 on upload failures

---

invenio_records_resources/records/api.py

* closes https://github.com/zenodo/rdm-project/issues/547
:warning: IMPORTANT: For this change to have effect it requires to reindex all records as the file types are indexed in OS

api: get file extension from key

---

invenio_records_resources/resources/files/resource.py

* closes https://github.com/zenodo/rdm-project/issues/471
Affects "Download all" button in the files (and media files) previewer. Downloads an archive with only healthy files

files archive: handle broken files

---

.github/workflows/tests.yml
invenio_records_resources/services/custom_fields/date.py

- custom_fields: fix EDTF datetime field
- ci: update db, search, and python matrix

Custom fields EDTF fix and CI update

---

invenio_records_resources/services/records/queryparser/__init__.py
invenio_records_resources/services/records/queryparser/query.py
invenio_records_resources/services/records/queryparser/transformer.py
tests/services/test_service_queryparser.py

* Adds support for dynamically mapping values in a query to other values, e.g. "communities:blr" to "communities:1234".
**Reminder**
2. You agree …

Query parser: Map search field values

---

invenio_records_resources/records/models.py

- Partially addresses https://github.com/inveniosoftware/invenio-rdm-records/issues/1500
- Adds an index on the `record_id` FK column (for faster listing of all record files)
- Fixes the unique index on `(record_id, key)`, to make sure we don't get duplicate file keys on records.

models: fix record file indices

---

invenio_records_resources/services/records/schema.py

There seems to an issue with marshmallow that they are not freezing the original data which causes potential modifications leading to an updated copy of the object on subsequent pre/validate/post calls.
https://github.com/marshmallow-code/marshmallow/blob/13a12ad2eed262933770c643febbc46d4905c4c9/src/marshmallow/schema.py#L851-L853
This is work around for that for this specific case https://github.com/inveniosoftware/invenio-communities/pull/1088 where we need to use `pass_original`.

schema: fix data reference update in pre_load

---

.gitignore
invenio_records_resources/services/records/facets/__init__.py
invenio_records_resources/services/records/facets/facets.py
invenio_records_resources/services/records/facets/response.py
tests/mock_module/config.py
tests/mock_module/mappings/os-v1/records/record-v1.0.0.json
tests/mock_module/mappings/os-v2/records/record-v1.0.0.json
tests/mock_module/mappings/v7/records/record-v1.0.0.json
tests/mock_module/schemas.py
tests/resources/test_resource_faceting.py
tests/services/test_service_facets.py

This approach doesn't use 'nested' fields, but instead relies on a
field containing `<parent><split char><child>` to aggregate correctly.
- Alternative to: https://github.com/inveniosoftware/invenio-records-resources/pull/546
- Part of closing: https://github.com/inveniosoftware/invenio-rdm-records/issues/798

facets: provide CombinedTermsFacet to fix #798 [+]

---

invenio_records_resources/config.py
invenio_records_resources/services/files/transfer.py
tests/services/files/test_file_service.py

* Added config option to allow empty files to be uploaded.
* Added tests for empty files.

services: allow empty files to be uploaded

---

invenio_records_resources/services/files/processors/base.py
invenio_records_resources/services/files/processors/image.py

- If `pyvips` (and `libvips` on sysstem) are installed, PyVIPS is used to extract width and height for images.
- Compared to Wand, PyVIPS has the benefit of not loading the entire image in memory to extract width/height metadata for the image (works for multi-layer images also, such as TIFFs and PDFs). See [this gist](https://gist.github.com/slint/55c4ca8e1c59775e73942d4424a62c67) for a small memory analysis.

processors: optionally use PyVIPS for image metadata

---

invenio_records_resources/services/uow.py
tests/services/files/test_files_processing.py

closes https://github.com/inveniosoftware/invenio-jobs/issues/6 (edited  by @alejandromumo  🥷)
Earlier `TaskOp` used the Celery task delay method, so the signature of init was with respect to delay. However, now we also want to pass execution options which are only possible through `apply_async` (Ref for the signature difference: https://docs.celeryq.dev/en/stable/userguide/calling.html#example).
The `for_apply_async` receives `apply_async` compatible arguments and returns a valid `TaskOp` while using `TaskOp` directly will support the existing signature of `delay`, for backwards compatibility.

uow: update TaskOp; add TaskRevokeOp

---

invenio_records_resources/records/systemfields/files/manager.py

We calculate image metadata when files are committed, which can happen on record edit as well. 
Right now we only sync the file object version but not the metadata on edit - this PR fixes that.

files: sync metadata on file edit

---

invenio_records_resources/services/records/queryparser/transformer.py
tests/services/test_service_queryparser.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/240

queryparser: add RestrictedTerm to exclude allowed phrases by permission

---

invenio_records_resources/services/records/config.py

This pull request fixes premature evaluation of i18n strings inside static fields. gettext call, that causes
the evaluation to be performed at boot time, was replaced with gettext_lazy that is performed at
request time. This fixes sort options not being translated when language is changed.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-serv …

Using lazy_gettext in boot-time translations

---

CHANGES.rst
invenio_records_resources/resources/files/resource.py

* flask uses now the MAX_CONTENT_LENGTH to restrict file upload. it is
possible to set the max_content_length per request. so for this request
it is set to the configured max file size
NOTE:
needs https://github.com/inveniosoftware/invenio-oauth2server/pull/272

fix: file upload >100MB

---

invenio_records_resources/resources/files/resource.py

* Setting the return code directly hides the return code that ``send_file`` might be issuing, resulting in odd situations when the storage layer returns a 302, i.e. offload download.
---
When an instance uses local storage, eventually [send_file](https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/helpers.py#L62) gets called and the file is streamed through the application server.
If one uses Invenio-S3,  instead of serving the file directly, the application [issues a redirect](https://github.com/inveniosoftware/invenio-s3/blob/master/invenio_s3/helpers.py#L20) to a short-lived signed URL, relaying the work of streaming the file to the storage server, offloading.
The problem is that send_file itself returns a response with its own response code, etc. The …

files: remove HTTP code from read_content

---

invenio_records_resources/records/systemfields/entity_reference.py
invenio_records_resources/resources/errors.py
invenio_records_resources/services/custom_fields/errors.py
invenio_records_resources/services/errors.py
invenio_records_resources/services/files/service.py
invenio_records_resources/services/records/params/pagination.py
invenio_records_resources/services/records/params/querystr.py
invenio_records_resources/services/records/params/sort.py
invenio_records_resources/services/records/queryparser/transformer.py
setup.cfg

Fix: some strings that could appear inside UI were not marked with gettext/lazy_gettext.
This PR adds lazy_gettext into places where the string is read when invenio is started (static initialization) and gettext elsewhere
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
1. …

i18n: Fix untranslated strings in facets

---

invenio_records_resources/services/records/results.py

* Sometimes, keys relevant to the serialization process are not included inside ``_source``, i.e. "highlight." By adding ``hit.meta`` as part of the serializer context, we make them available without the risk of name collision.

services: include Opensearch meta in the results

---

invenio_records_resources/services/custom_fields/date.py
tests/services/custom_fields/test_date_cf.py

This fixes #634 
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.

Fix EDTFDateStringCF dump/load to support multiple values

---

invenio_records_resources/services/files/processors/image.py

* UserWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html. The
pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.

fix: pkg_resources DeprecationWarning

---

invenio_records_resources/records/systemfields/entity_reference.py
invenio_records_resources/services/records/results.py
invenio_records_resources/services/references/__init__.py
invenio_records_resources/services/references/schema.py

Moved from https://github.com/inveniosoftware/invenio-requests/pull/431
Closes https://github.com/inveniosoftware/invenio-requests/issues/428

service: records: add MultiFieldsResolver

---

invenio_records_resources/services/files/tasks.py

In our tests (with local file storage), multipart-uploaded files did not have a checksum set at all (it was set to `None`), which caused the task `recompute_multipart_checksum_task()` to fail.
This PR handles the case that the checksum is set to `None` in the task.
However, I'm not sure if that's just symptom treatment, and it would make more sense instead to make sure that every uploaded part's checksum were calculated and stored instead?
Ping @mesemus

fix(multipart): recompute full file checksum if no parts are set
